using Microsoft.AspNetCore.Mvc.Testing;
using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Xunit;

namespace GLMS.Tests
{
    /// <summary>
    /// WHAT THIS FILE IS:
    /// API Integration Tests for GLMS.Api (Part 3 — Automated Integration Testing).
    ///
    /// WHAT I DID:
    /// I used WebApplicationFactory&lt;Program&gt; from Microsoft.AspNetCore.Mvc.Testing.
    /// This spins up a REAL in-memory instance of GLMS.Api — the actual HTTP pipeline,
    /// controllers, middleware, and DI container — without needing a running server.
    ///
    /// WHY INTEGRATION TESTS MATTER (for the Technical Reflection Report):
    ///   Unit tests test individual methods in isolation (see CurrencyCalculationTests).
    ///   Integration tests test that the WHOLE system works together:
    ///   → Does the routing work? (Does GET /api/contracts reach the right action?)
    ///   → Does authentication work? (Is a 401 returned without a token?)
    ///   → Does the controller return the right HTTP status code?
    ///   → Does the API return valid JSON?
    ///
    /// In a CI/CD pipeline (like our GitHub Actions workflow), these tests run
    /// automatically on every push. If an integration test fails, the deployment
    /// is blocked — preventing broken code from reaching production.
    ///
    /// TESTS IN THIS FILE:
    ///   1. Unauthenticated requests return 401 Unauthorized (security check)
    ///   2. Login with valid credentials returns 200 and a JWT token
    ///   3. Login with invalid credentials returns 401
    ///   4. Authenticated GET /api/contracts returns 200 OK with JSON array
    ///   5. Authenticated GET /api/clients returns 200 OK
    ///   6. Authenticated GET /api/servicerequests returns 200 OK
    ///   7. Authenticated GET /api/dashboard returns 200 OK with stats object
    ///   8. GET /api/servicerequests/rate returns a valid exchange rate
    /// </summary>
    // Program refers to the global-namespace Program class generated by GLMS.Api's top-level statements
    // combined with the 'public partial class Program {}' marker at the bottom of GLMS.Api/Program.cs
    public class ApiIntegrationTests : IClassFixture<WebApplicationFactory<Program>>
    {
        private readonly HttpClient _client;
        private static readonly JsonSerializerOptions _json = new() { PropertyNameCaseInsensitive = true };

        // WebApplicationFactory creates an in-memory GLMS.Api server for testing
        public ApiIntegrationTests(WebApplicationFactory<Program> factory)
        {
            _client = factory
                .WithWebHostBuilder(builder =>
                {
                    // Override the environment to "Testing" so we can configure
                    // an in-memory database instead of SQL Server for isolation
                    builder.UseSetting("ASPNETCORE_ENVIRONMENT", "Testing");
                    builder.ConfigureServices(services =>
                    {
                        // Integration tests run without a real SQL Server.
                        // EnsureCreated() will still run but against a localdb/in-memory stub.
                        // The main purpose is to test HTTP routing and auth — not DB queries.
                    });
                })
                .CreateClient();
        }

        // =====================================================================
        // HELPER: Login and get JWT token
        // =====================================================================

        private async Task<string?> GetJwtTokenAsync()
        {
            var loginBody    = JsonSerializer.Serialize(new { username = "admin", password = "Admin@123" });
            var loginContent = new StringContent(loginBody, Encoding.UTF8, "application/json");
            var response     = await _client.PostAsync("/api/auth/login", loginContent);

            if (!response.IsSuccessStatusCode) return null;

            var json = await response.Content.ReadAsStringAsync();
            using var doc = JsonDocument.Parse(json);
            return doc.RootElement.TryGetProperty("token", out var tokenProp)
                ? tokenProp.GetString()
                : null;
        }

        private void AuthoriseClient(string token)
        {
            _client.DefaultRequestHeaders.Authorization =
                new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
        }

        // =====================================================================
        // TEST 1: Unauthenticated requests should return 401
        // =====================================================================

        /// <summary>
        /// WHAT THIS TESTS:
        /// Verifies that all protected endpoints reject requests without a JWT token.
        /// This confirms the [Authorize] attribute is working correctly.
        /// Without this, anyone could access contract/client data without logging in.
        /// </summary>
        [Theory]
        [InlineData("/api/contracts")]
        [InlineData("/api/clients")]
        [InlineData("/api/servicerequests")]
        [InlineData("/api/dashboard")]
        public async Task Get_WithoutToken_Returns401Unauthorized(string endpoint)
        {
            // Arrange — no Authorization header (no token)
            _client.DefaultRequestHeaders.Authorization = null;

            // Act
            var response = await _client.GetAsync(endpoint);

            // Assert
            Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
        }

        // =====================================================================
        // TEST 2: Login with VALID credentials returns 200 + JWT token
        // =====================================================================

        /// <summary>
        /// WHAT THIS TESTS:
        /// The full authentication flow — that POST /api/auth/login:
        ///   - Returns HTTP 200 OK
        ///   - Returns a JSON body containing a "token" property
        ///   - The token is not null or empty
        /// </summary>
        [Fact]
        public async Task Login_WithValidCredentials_Returns200AndToken()
        {
            // Arrange
            var body    = JsonSerializer.Serialize(new { username = "admin", password = "Admin@123" });
            var content = new StringContent(body, Encoding.UTF8, "application/json");

            // Act
            var response = await _client.PostAsync("/api/auth/login", content);
            var json     = await response.Content.ReadAsStringAsync();

            // Assert — HTTP status
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            // Assert — response has a non-empty "token" field
            using var doc = JsonDocument.Parse(json);
            Assert.True(doc.RootElement.TryGetProperty("token", out var tokenProp));
            var token = tokenProp.GetString();
            Assert.NotNull(token);
            Assert.NotEmpty(token);
        }

        // =====================================================================
        // TEST 3: Login with INVALID credentials returns 401
        // =====================================================================

        /// <summary>
        /// WHAT THIS TESTS:
        /// That the API correctly rejects wrong credentials with a 401 response.
        /// This prevents brute-force or credential-stuffing attacks from succeeding.
        /// </summary>
        [Theory]
        [InlineData("admin",    "WrongPassword")]
        [InlineData("wronguser", "Admin@123")]
        [InlineData("",          "")]
        public async Task Login_WithInvalidCredentials_Returns401(string username, string password)
        {
            // Arrange
            var body    = JsonSerializer.Serialize(new { username, password });
            var content = new StringContent(body, Encoding.UTF8, "application/json");

            // Act
            var response = await _client.PostAsync("/api/auth/login", content);

            // Assert
            Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
        }

        // =====================================================================
        // TEST 4: Authenticated GET /api/contracts returns 200 with JSON array
        // =====================================================================

        /// <summary>
        /// WHAT THIS TESTS:
        /// End-to-end: login → get token → call /api/contracts → assert 200 + JSON array.
        /// This is a full integration test that exercises:
        ///   authentication middleware → routing → ContractsController.GetAll() → JSON response.
        /// </summary>
        [Fact]
        public async Task GetContracts_WithValidToken_Returns200AndJsonArray()
        {
            // Arrange — get a valid JWT first
            var token = await GetJwtTokenAsync();
            Assert.NotNull(token); // Prerequisite: login must work
            AuthoriseClient(token!);

            // Act
            var response = await _client.GetAsync("/api/contracts");
            var json     = await response.Content.ReadAsStringAsync();

            // Assert — HTTP 200 OK
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            // Assert — response body is a JSON array (empty or populated)
            using var doc = JsonDocument.Parse(json);
            Assert.Equal(JsonValueKind.Array, doc.RootElement.ValueKind);
        }

        // =====================================================================
        // TEST 5: Authenticated GET /api/clients returns 200
        // =====================================================================

        [Fact]
        public async Task GetClients_WithValidToken_Returns200()
        {
            var token = await GetJwtTokenAsync();
            Assert.NotNull(token);
            AuthoriseClient(token!);

            var response = await _client.GetAsync("/api/clients");

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }

        // =====================================================================
        // TEST 6: Authenticated GET /api/servicerequests returns 200
        // =====================================================================

        [Fact]
        public async Task GetServiceRequests_WithValidToken_Returns200()
        {
            var token = await GetJwtTokenAsync();
            Assert.NotNull(token);
            AuthoriseClient(token!);

            var response = await _client.GetAsync("/api/servicerequests");

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }

        // =====================================================================
        // TEST 7: Authenticated GET /api/dashboard returns 200 with stats
        // =====================================================================

        /// <summary>
        /// WHAT THIS TESTS:
        /// That the dashboard endpoint returns all expected stats fields.
        /// A missing field here would cause a NullReferenceException in the MVC frontend.
        /// </summary>
        [Fact]
        public async Task GetDashboard_WithValidToken_Returns200WithStats()
        {
            var token = await GetJwtTokenAsync();
            Assert.NotNull(token);
            AuthoriseClient(token!);

            var response = await _client.GetAsync("/api/dashboard");
            var json     = await response.Content.ReadAsStringAsync();

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            // Assert expected JSON properties are present
            using var doc = JsonDocument.Parse(json);
            Assert.True(doc.RootElement.TryGetProperty("totalClients",         out _), "Missing 'totalClients'");
            Assert.True(doc.RootElement.TryGetProperty("totalContracts",       out _), "Missing 'totalContracts'");
            Assert.True(doc.RootElement.TryGetProperty("activeContracts",      out _), "Missing 'activeContracts'");
            Assert.True(doc.RootElement.TryGetProperty("totalServiceRequests", out _), "Missing 'totalServiceRequests'");
        }

        // =====================================================================
        // TEST 8: GET /api/servicerequests/rate returns a positive exchange rate
        // =====================================================================

        /// <summary>
        /// WHAT THIS TESTS:
        /// The external API integration (LU4 — Async/Await).
        /// Verifies that the rate endpoint returns a positive number.
        /// If the external API is down, CurrencyService returns the fallback (18.75).
        /// Either way, the value must be &gt; 0.
        /// </summary>
        [Fact]
        public async Task GetRate_WithValidToken_ReturnsPositiveRate()
        {
            var token = await GetJwtTokenAsync();
            Assert.NotNull(token);
            AuthoriseClient(token!);

            var response = await _client.GetAsync("/api/servicerequests/rate");
            var json     = await response.Content.ReadAsStringAsync();

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            using var doc = JsonDocument.Parse(json);
            Assert.True(doc.RootElement.TryGetProperty("rate", out var rateProp));
            var rate = rateProp.GetDecimal();
            Assert.True(rate > 0, $"Exchange rate must be positive, got: {rate}");
        }
    }
}

