using System.ComponentModel.DataAnnotations;

namespace GLMS.Shared.Models
{
    /// <summary>
    /// Represents a client (organisation or individual) managed by TechMove.
    /// A Client can hold multiple Contracts (one-to-many relationship).
    /// Validation attributes are shared with the API and the MVC views so that
    /// business rules are enforced in a single place.
    /// </summary>
    public class Client
    {
        /// <summary>Primary key — generated by the database.</summary>
        public int Id { get; set; }

        /// <summary>The client's full legal name.</summary>
        [Required]
        [StringLength(150)]
        [Display(Name = "Full Name")]
        public string Name { get; set; } = string.Empty;

        /// <summary>Primary contact e-mail address.</summary>
        [Required]
        [EmailAddress]
        [StringLength(200)]
        public string Email { get; set; } = string.Empty;

        /// <summary>Primary contact phone number.</summary>
        [Required]
        [Phone]
        [StringLength(20)]
        [Display(Name = "Phone Number")]
        public string Phone { get; set; } = string.Empty;

        /// <summary>Geographic region the client operates in (e.g., Western Cape, EMEA).</summary>
        [Required]
        [StringLength(100)]
        public string Region { get; set; } = string.Empty;

        /// <summary>Navigation property — all contracts belonging to this client.</summary>
        public ICollection<Contract> Contracts { get; set; } = new List<Contract>();
    }
}
