using System.ComponentModel.DataAnnotations;

namespace GLMS.Shared.Models
{
    /// <summary>
    /// Represents a service contract between TechMove and a Client.
    /// Contracts are created via the Factory Method Pattern (Local or International).
    /// Status changes trigger the Observer Pattern (ServiceRequestObserver, FinanceObserver).
    /// </summary>
    public class Contract
    {
        /// <summary>Primary key — generated by the database.</summary>
        public int Id { get; set; }

        /// <summary>Foreign key linking this contract to its owner Client.</summary>
        [Required]
        [Display(Name = "Client")]
        public int ClientId { get; set; }

        /// <summary>Navigation property — the Client who owns this contract.</summary>
        public Client? Client { get; set; }

        /// <summary>The date from which the contract is effective.</summary>
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; } = DateTime.Today;

        /// <summary>The date on which the contract expires.</summary>
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; } = DateTime.Today.AddYears(1);

        /// <summary>
        /// Current lifecycle state of the contract.
        /// Changing this status fires the Observer pattern notifications.
        /// </summary>
        public ContractStatus Status { get; set; } = ContractStatus.Draft;

        /// <summary>The service tier agreed upon (Basic, Standard, or Premium).</summary>
        [Required]
        [Display(Name = "Service Level")]
        public ServiceLevel ServiceLevel { get; set; } = ServiceLevel.Standard;

        /// <summary>Whether this is a local or international contract (drives the Factory pattern).</summary>
        [Required]
        [Display(Name = "Contract Type")]
        public ContractType ContractType { get; set; } = ContractType.Local;

        /// <summary>Relative path to the uploaded signed agreement PDF stored on the server.</summary>
        [Display(Name = "Signed Agreement (PDF)")]
        public string? SignedAgreementPath { get; set; }

        /// <summary>The original file name of the uploaded PDF (before UUID renaming).</summary>
        [Display(Name = "Original File Name")]
        public string? SignedAgreementOriginalName { get; set; }

        /// <summary>Navigation property — all service requests raised under this contract.</summary>
        public ICollection<ServiceRequest> ServiceRequests { get; set; } = new List<ServiceRequest>();
    }
}
