using System.ComponentModel.DataAnnotations;

namespace GLMS.Shared.Models
{
    /// <summary>
    /// Represents a service request raised under a Contract.
    /// Currency conversion (USD → ZAR) is performed at creation time using the
    /// Strategy Pattern (UsdToZarStrategy + FinancialProcessor) and the live
    /// exchange rate from the ExchangeRate-API.
    /// A ServiceRequest cannot be created if its parent Contract is Expired or OnHold.
    /// </summary>
    public class ServiceRequest
    {
        /// <summary>Primary key — generated by the database.</summary>
        public int Id { get; set; }

        /// <summary>Foreign key linking this request to its parent Contract.</summary>
        [Required]
        [Display(Name = "Contract")]
        public int ContractId { get; set; }

        /// <summary>Navigation property — the parent Contract.</summary>
        public Contract? Contract { get; set; }

        /// <summary>A description of the service work to be performed.</summary>
        [Required]
        [StringLength(500)]
        public string Description { get; set; } = string.Empty;

        /// <summary>The cost of this service request denominated in US Dollars.</summary>
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Cost must be greater than zero.")]
        [Display(Name = "Cost (USD)")]
        [DataType(DataType.Currency)]
        public decimal CostUSD { get; set; }

        /// <summary>
        /// The cost converted to South African Rand.
        /// Calculated at creation time using the live exchange rate.
        /// </summary>
        [Display(Name = "Cost (ZAR)")]
        [DataType(DataType.Currency)]
        public decimal CostZAR { get; set; }

        /// <summary>The exchange rate (USD → ZAR) that was used at the time of creation.</summary>
        [Display(Name = "Exchange Rate (USD→ZAR)")]
        public decimal ExchangeRateUsed { get; set; }

        /// <summary>The current processing state of this service request.</summary>
        [Required]
        public ServiceRequestStatus Status { get; set; } = ServiceRequestStatus.Pending;

        /// <summary>UTC timestamp of when this service request was created.</summary>
        [Display(Name = "Date Created")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
